name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # 히스토리 부족으로 인한 push 실패 방지

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-leetcode

      - name: Run update.py
        run: |
          python update.py

      - name: Configure git (local)
        run: |
          git config user.name 'RKDLDE'
          git config user.email 'kangcanddy@gmail.com'

      - name: Commit changes if any
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          # 혹시 동시 푸시로 인한 non-fast-forward 방지
          git pull --rebase origin main || true
          git commit -m "auto update README.md [skip ci]"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin HEAD:main
